### ISSUE TITLE
Fan Switch Appearing As Light Entity

### ISSUE THREAD

**Issue by sjdvda** [tuya/tuya-home-assistant#463] opened 2021-09-12 23:00 UTC
**Describe the bug**
I have a [MiniTiger Tuya ceiling fan switch](https://www.aliexpress.com/item/33020083165.html). It showed up as a fan entity when using the built-in Tuya integration but is appearing as a light entity when using this one. I'm able to turn it on and off and control the fan speed using the "brightness" slider.

**Expected behavior**
The fan switch should show up as a fan.

Note: using the template fan platform is an easy workaround but I believe this should be supported natively.

**Screenshots**
![image](https://user-images.githubusercontent.com/2962486/133005096-c811504f-981c-4059-ae19-aa66074b92de.png)
![image](https://user-images.githubusercontent.com/2962486/133005120-48216264-09d0-4275-91f1-79b27a891f9f.png)

**Home Assistant Version**
- 2021.9.6

**Device info**

```
"active_time": 1568054479,
"biz_type": 18,
"category": "dj",
"create_time": 1568054479,
"icon": "smart/icon/1502782566_0.png",
"id": "83054170840d8e917ea2",
"ip": "***",
"lat": "***",
"local_key": "***",
"lon": "***",
"model": "WF-FS01",
"name": "Ceiling Fan",
"online": true,
"owner_id": "2424314",
"product_id": "E2yFTieOV8kd5bOB",
"product_name": "Fan switch",
"status": [
{
"code": "switch_led",
"value": false
},
{
"code": "bright_value",
"value": 11
}
],
"sub": false,
"time_zone": "+04:00",
"uid": "***",
"update_time": 1631477752,
"uuid": "83054170840d8e917ea2"
},
```

**Device specifications**

```
2021-09-13 02:49:31 DEBUG (SyncWorker_7) [tuya iot] Response: {
"result": {
"category": "dj",
"functions": [
{
"code": "switch_led",
"type": "Boolean",
"values": "{}"
},
{
"code": "bright_value",
"type": "Integer",
"values": "{\"min\":25,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}"
}
],
"status": [
{
"code": "switch_led",
"type": "Boolean",
"values": "{}"
},
{
"code": "bright_value",
"type": "Integer",
"values": "{\"min\":25,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}"
}
]
},
"success": true,
"t": 1631486971166
}
```

**Comment by cvroque** [comment] 2021-09-13 18:17
Just for reference, your device category is "dj" which by the official docs is reserved for [lights](https://developer.tuya.com/en/docs/iot/categorydj?id=Kaiuyzy3eheyy).
The category for ceiling fan lights should be "fsd" or "fs", so in your case we should wait for an official reply from tuya devs.

**Comment by nominefi** [comment] 2021-11-10 16:34
Hi, I have that fan controller and it also detects me as light, until a few days ago with the brightness bar it managed the speed, but now it does not work. I can turn it on and off but not change the speed even if I raise or lower the brightness bar. I think a couple of updates ago it stopped working.
Does the glow bar still work for you?
Thank you

**Comment by almighty059** [comment] 2021-11-27 12:19
@nominefi is your fan switch still not working? I had a Treatlife DS03 connected but I got aggravated with the constant problems so I decided to separate the fan and light control into two separate switches. I just made the switch a couple of days ago. I bought a Treatlight fan switch because it's a 4-speed switch like my fan. It worked fine the first day and then I lost the entity and it is now only listed as a device. I tried to connect it with the Local Tuya Integration but I am only able to control the on/off function. The speed control through HA no longer works. There's not a lot of smart switches specifically for fans and most of the ones available have issues.

**Comment by nominefi** [comment] 2021-11-30 11:03
Hi, I'm still the same, I can turn the fan on and off but not regulate it. I don't know if it's Tuya or homeassistant's problem. In Tuya app if it detects me as a fan

**Comment by frenck** [comment] 2022-02-03 09:23
Yesterday, Home Assistant 2022.2 was released.
Could you try upgrading to that version and see if the issue has been resolved?

If not, Home Assistant 2022.2 contains a new diagnostic tool. There is now a "Download Diagnostics" button on each Tuya device on the device page. Clicking that button will download diagnostics information for that specific device. Drag the downloaded file into this issue. It will help with finding out what the problem is.

**Comment by jodasm** [comment] 2022-02-03 09:57
I've got a similar issue.

![image](https://user-images.githubusercontent.com/10863992/152320366-a00fbfd0-ed6d-4efd-81ee-c7d9a09274e9.png)
[tuya-ed87fb2c1839d905f9828999b793daf7-Bed1 Fan Switch-f3fc61e7a70ed3f6fbb15845b719adb2.json.txt](https://github.com/tuya/tuya-home-assistant/files/7993483/tuya-ed87fb2c1839d905f9828999b793daf7-Bed1.Fan.Switch-f3fc61e7a70ed3f6fbb15845b719adb2.json.txt)

Let me know if I should be creating my own thread.

**Comment by frenck** [comment] 2022-02-03 10:02
@jodasm According to that dump

```json
    "tuya_v2": {
      "version": "1.5.0",
      "requirements": [
        "tuya-iot-py-sdk==0.4.1"
      ]
    }
```

You are running the old Tuya V2 custom integration. That one has been removed and is no longer maintained. Please remove that custom integration and use the version that is shipped/built into Home Assistant itself.

**Comment by jodasm** [comment] 2022-02-03 10:29
Sorry I wasn't using that.  Had both installed.
Here's the dump again after I removed that custom component.

And added back the Home Assistant Tuya integration.

[tuya-246c8c8ff2ba65059b6eb975306794b6-Gym Motion Detector-4d79e72cfecb933837f4aa7d14876bc6.json.txt](https://github.com/tuya/tuya-home-assistant/files/7993688/tuya-246c8c8ff2ba65059b6eb975306794b6-Gym.Motion.Detector-4d79e72cfecb933837f4aa7d14876bc6.json.txt)

**Comment by frenck** [comment] 2022-02-03 10:30
> Sorry I wasn't using that. Had both installed.

Having both installed will cause issues :)

Thanks for the dump, I will take a look

**Comment by frenck** [comment] 2022-02-03 10:32
@jodasm I think you dumped the wrong device?

```json
    "name": "Gym Motion Detector",
    "model": "Starlux DET100HA",
    "category": "pir",
```

That is what is in the dump, which of course isn't a fan.

**Comment by jodasm** [comment] 2022-02-03 10:33
sorry updated

**Comment by jodasm** [comment] 2022-02-03 10:34
I just looked at the lovelace card and can now see this.

![image](https://user-images.githubusercontent.com/10863992/152326167-fb694bdf-7a69-4404-b3b3-50adbc133f02.png)

**Comment by frenck** [comment] 2022-02-03 10:42
That looks correct, right?

**Comment by sjdvda** [comment] 2022-02-03 10:54
My ceiling fan switch is still showing up as a light, even after updating to 2022.1:
![image](https://user-images.githubusercontent.com/2962486/152328754-87a1881f-0e1f-4735-9fd1-87147d3ef379.png)

[tuya-8aa2e7d04ed1e4f86f688b46a223d49a-Ceiling Fan-931b761816fdf0508c4644713343ade9.json.txt](https://github.com/tuya/tuya-home-assistant/files/7993864/tuya-8aa2e7d04ed1e4f86f688b46a223d49a-Ceiling.Fan-931b761816fdf0508c4644713343ade9.json.txt)

Is there any way I can override the manufacturer settings and change the device category from "dj" to a fan type?

**Comment by frenck** [comment] 2022-02-03 10:58
@sjdvda 

Thanks for sharing the diagnostics.
This shows the device is a light.

```json
    "category": "dj",
```

This is a fault at the manufacturer and not a bug for the integration.


> Is there any way I can override the manufacturer settings and change the device category from "dj" to a fan type?

No, that is not possible. It even uses brightness control the fan speed 🤷 

There is not much we can do about this. As a workaround, you could use a fan template to interact with the light entity (to create an actual fan in Home Assistant).

https://www.home-assistant.io/integrations/fan.template

Other than that, there is not much we can do otherwise.

For that reason, I'm closing this issue, as there is nothing that can be improved on the integration in this matter.

**Closed by frenck** 2022-02-03 10:58 UTC
Labels: bug
