### ISSUE TITLE
Temp and hum sensor TT081

### ISSUE THREAD

**Issue by czmatt** [tuya/tuya-home-assistant#461] opened 2021-09-12 10:47 UTC
**Device normal info**
- Brand Choifoo
- Model TT081 zigbee
- Device works well in Tuya Smart app (seems there is one update per hour, inc battery level)
- HA Tuya v2 v1.5.0
Thanks

**Device info 
{
"active_time": 1631347950,
"biz_type": 0,
"category": "wsdcg",
"create_time": 1631347950,
"icon": "smart/icon/ay1537005524478pGtw5/d29f15333bff54503598a7ea561c8497.png",
"id": "XXX4b9b5d7b91c287XXX",
"ip": "***",
"lat": "***",
"local_key": "***",
"lon": "***",
"model": "TT081",
"name": "Temp and Hum chambre",
"node_id": "60a423fffe2c73c1",
"online": true,
"owner_id": "35613126",
"product_id": "gqhxixyk",
"product_name": "Temp and Hum",
"status": [],
"sub": true,
"time_zone": "+02:00",
"uid": "***",
"update_time": 1631347969,
"uuid": "60a423fffe2c73c1"
},

**Device specifications
2021-09-12 12:28:11 DEBUG (SyncWorker_3) [tuya iot] Request: method = GET, url = https://openapi.tuyaeu.com/v1.0/devices/XXX4b9b5d7b91c287XXX/specifications, params = None, body = None, t = 1631442491045
2021-09-12 12:28:11 DEBUG (SyncWorker_3) [tuya iot] Response: {
"code": 2009,
"msg": "not support this device",
"success": false,
"t": 1631442491099
}

**Comment by papou-github** [comment] 2021-12-10 08:38
Hi, 
Same issues and was working in previous api.

**Comment by frenck** [comment] 2022-02-03 09:24
Yesterday, Home Assistant 2022.2 was released.
Could you try upgrading to that version and see if the issue has been resolved?

If not, Home Assistant 2022.2 contains a new diagnostic tool. There is now a "Download Diagnostics" button on each Tuya device on the device page. Clicking that button will download diagnostics information for that specific device. Drag the downloaded file into this issue. It will help with finding out what the problem is.

**Comment by czmatt** [comment] 2022-02-12 10:25
Hi, thank you for the update and your contribution !
I’ve installed the new release.
Same behavior with this device
Below the diag log 
Best
Matthieu

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.2.6",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.9.7",
    "docker": true,
    "arch": "armv7l",
    "timezone": "Europe/Paris",
    "os_name": "Linux",
    "os_version": "5.10.92-v7",
    "supervisor": "2022.01.1",
    "host_os": "Home Assistant OS 7.3",
    "docker_version": "20.10.9",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.22.0",
      "requirements": [
        "aiogithubapi>=21.11.0"
      ]
    },
    "alexa_media": {
      "version": "3.10.15",
      "requirements": [
        "alexapy==1.25.3",
        "packaging>=20.3",
        "wrapt>=1.12.1"
      ]
    },
    "gazpar": {
      "version": "0.0.3",
      "requirements": [
        "requests==2.25.1"
      ]
    },
    "linky": {
      "version": "1.0",
      "requirements": [
        "requests==2.24.0"
      ]
    }
  },
  "integration_manifest": {
    "domain": "tuya",
    "name": "Tuya",
    "documentation": "https://www.home-assistant.io/integrations/tuya",
    "requirements": [
      "tuya-iot-py-sdk==0.6.6"
    ],
    "dependencies": [
      "ffmpeg"
    ],
    "codeowners": [
      "@Tuya",
      "@zlinoliver",
      "@METISU",
      "@frenck"
    ],
    "config_flow": true,
    "iot_class": "cloud_push",
    "dhcp": [
      {
        "macaddress": "105A17*"
      },
      {
        "macaddress": "10D561*"
      },
      {
        "macaddress": "1869D8*"
      },
      {
        "macaddress": "381F8D*"
      },
      {
        "macaddress": "508A06*"
      },
      {
        "macaddress": "68572D*"
      },
      {
        "macaddress": "708976*"
      },
      {
        "macaddress": "7CF666*"
      },
      {
        "macaddress": "84E342*"
      },
      {
        "macaddress": "D4A651*"
      },
      {
        "macaddress": "D81F12*"
      }
    ],
    "is_built_in": true
  },
  "data": {
    "endpoint": "https://openapi.tuyaeu.com",
    "auth_type": 0,
    "country_code": "33",
    "app_type": "tuyaSmart",
    "mqtt_connected": true,
    "disabled_by": null,
    "disabled_polling": false,
    "name": "Temp and Hum chambre",
    "model": "TT081",
    "category": "wsdcg",
    "product_id": "gqhxixyk",
    "product_name": "Temp and Hum",
    "online": true,
    "sub": true,
    "time_zone": "+02:00",
    "active_time": "2021-09-11T08:12:30+00:00",
    "create_time": "2021-09-11T08:12:30+00:00",
    "update_time": "2021-12-17T11:36:32+00:00",
    "function": {},
    "status_range": {},
    "status": {},
    "home_assistant": {
      "name": "Temp and Hum chambre",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": []
    }
  }
}

**Comment by papou-github** [comment] 2022-02-14 12:29
Hi,
Thank you for your help but same for me. Here is my diag or the tuya device:
Regards
Papou

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.2.6",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.9.7",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Paris",
    "os_name": "Linux",
    "os_version": "5.10.98",
    "supervisor": "2022.01.1",
    "host_os": "Home Assistant OS 7.4",
    "docker_version": "20.10.9",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "skodaconnect": {
      "version": "v1.0.62",
      "requirements": [
        "skodaconnect>=1.1.12",
        "homeassistant>=2021.09.0"
      ]
    },
    "hacs": {
      "version": "1.20.0",
      "requirements": [
        "aiogithubapi>=21.11.0"
      ]
    },
    "scheduler": {
      "version": "v0.0.0",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "tuya",
    "name": "Tuya",
    "documentation": "https://www.home-assistant.io/integrations/tuya",
    "requirements": [
      "tuya-iot-py-sdk==0.6.6"
    ],
    "dependencies": [
      "ffmpeg"
    ],
    "codeowners": [
      "@Tuya",
      "@zlinoliver",
      "@METISU",
      "@frenck"
    ],
    "config_flow": true,
    "iot_class": "cloud_push",
    "dhcp": [
      {
        "macaddress": "105A17*"
      },
      {
        "macaddress": "10D561*"
      },
      {
        "macaddress": "1869D8*"
      },
      {
        "macaddress": "381F8D*"
      },
      {
        "macaddress": "508A06*"
      },
      {
        "macaddress": "68572D*"
      },
      {
        "macaddress": "708976*"
      },
      {
        "macaddress": "7CF666*"
      },
      {
        "macaddress": "84E342*"
      },
      {
        "macaddress": "D4A651*"
      },
      {
        "macaddress": "D81F12*"
      }
    ],
    "is_built_in": true
  },
  "data": {
    "endpoint": "https://openapi.tuyaeu.com",
    "auth_type": 0,
    "country_code": "33",
    "app_type": "smartlife",
    "mqtt_connected": true,
    "disabled_by": null,
    "disabled_polling": false,
    "name": "TH-OfficePascal",
    "model": "TT081",
    "category": "wsdcg",
    "product_id": "gqhxixyk",
    "product_name": "Temp and Hum",
    "online": true,
    "sub": true,
    "time_zone": "+02:00",
    "active_time": "2021-11-11T09:53:49+00:00",
    "create_time": "2021-11-11T09:53:49+00:00",
    "update_time": "2021-11-30T08:59:57+00:00",
    "function": {},
    "status_range": {},
    "status": {},
    "home_assistant": {
      "name": "TH-OfficePascal",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": []
    }
  }
}

**Comment by frenck** [comment] 2022-02-14 13:12
@czmatt @papou-github 

In both your outputs:

```json
"function": {},
"status_range": {},
"status": {},
```

☝️  That is the information Home Assistant receives from the Tuya API about the functions and statuses your devices expose to us. As you can see, they are empty.

Thus Home Assistant is correctly handling it, as there is nothing to show. If you think that this is incorrect, I suggest on contacting Tuya directly by submitting a support ticket from your Tuya IoT account.

Closing this issue, as this is not an issue with the Home Asssistant implementation. We can't make up something that is not there.

**Closed by frenck** 2022-02-14 13:12 UTC
Labels: enhancement, help wanted

**Comment by estahn** [comment] 2022-10-08 09:29
@papou-github Did you get anywhere with this? I just lodged a ticket with Tuya Platform support team.
