### ISSUE TITLE
Temp and Humidity sensor unsupported in 2021.11

### ISSUE THREAD

**Issue by sagioto** [tuya/tuya-home-assistant#712] opened 2021-11-23 22:25 UTC
**Describe the bug**
My temp & hum sensor function correctly using the tuya app and in IoT cloud project but appear as unsupported in ha integration revealing no entities.

**Expected behavior**
Have sensor entities for temp and hum

**Home Assistant Version**
- 2021.11

**Device info 
Device Information

Product Name
温湿度传感器
Device ID
eb1e0a0***95gfid
Product Category
wsdcg
Device Status
Online
Activated At
2021-11-19 19:04:14
Device Association

Project
*
Association
*@gmail.com
Data Center
Western America Data Center
Extension Information

Sub-Device or Not
Yes
IP Address
--

**Comment by dragar** [comment] 2021-12-14 13:47
/usr/src/homeassistant/homeassistant/components/sensor/__init__.py
353: if native_unit_of_measurement in (TEMP_CELSIUS, TEMP_FAHRENHEIT):
             if self.hass is not None: **<- add this line for fast fix**
                return self.hass.config.units.temperature_unit
         return native_unit_of_measurement

and then works:
<img width="1512" alt="Screenshot 2021-12-14 at 14 45 26" src="https://user-images.githubusercontent.com/5007074/146010383-c7b790b9-c8b9-455c-a8f5-d1d488fd902f.png">

**Comment by sagioto** [comment] 2021-12-15 21:59
Is this scheduled to be in the next release?

**Comment by pserranoa** [comment] 2021-12-17 22:11
this workarround works for me

**Comment by magno-santos** [comment] 2021-12-20 15:45
I'm having dificulties on aplying thsi fix, since I don't have that folder. Should I create it?

**Comment by sagioto** [comment] 2021-12-23 13:14
I’m running in docker and don’t have that folder as well that’s why I used custom_compoent
The component is recognized when loading ha but the fix doesn’t work
Shouldn’t I see a null pointer exception in the logs without the fix?

**Comment by frenck** [comment] 2022-02-03 09:25
Yesterday, Home Assistant 2022.2 was released.
Could you try upgrading to that version and see if the issue has been resolved?

If not, Home Assistant 2022.2 contains a new diagnostic tool. There is now a "Download Diagnostics" button on each Tuya device on the device page. Clicking that button will download diagnostics information for that specific device. Drag the downloaded file into this issue. It will help with finding out what the problem is.

**Comment by magno-santos** [comment] 2022-02-03 20:11
Here you have the Diagnostics.


[tuya-25a2a56d1ece699e4db447264a7be229- Sensor Escritório-34e883c233d345804a5088436e697ff1.json.txt](https://github.com/tuya/tuya-home-assistant/files/7997846/tuya-25a2a56d1ece699e4db447264a7be229-.Sensor.Escritorio-34e883c233d345804a5088436e697ff1.json.txt)

**Comment by frenck** [comment] 2022-02-03 20:18
@magno-santos Looking at your data dump:

```json
    "function": {},
    "status_range": {},
    "status": {},
```

☝️ Those are the functions and statuses the Tuya API provides to work with. As you can see, it provides nothing, thus Home Assistant won't be able to do anything either.

In you cause, I would recommend to submit an ticket with Tuya, asking if they can do anything about it (log in to your Tuya IoT account to do that).

Sorry! wish I had better news to share with you.

../Frenck

**Comment by gemmaharton** [comment] 2022-02-06 21:34
So, playing with the api, the device itself doesn't provide the functions, but when querying the category it does. Is there some way to get ha to revert to querying the category if the device returns empty?
GET "https://openapi.tuyaus.com/v1.0/iot-03/categories/wsdcg/functions"
`{
  "result": {
    "category": "wsdcg",
    "functions": [
      {
        "code": "sampling_temperature",
        "desc": "sampling temperature",
        "name": "sampling temperature",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":3600,\"scale\":0,\"step\":1}"
      },
      {
        "code": "sampling_humidity",
        "desc": "sampling humidity",
        "name": "sampling humidity",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":3600,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_unit_convert",
        "desc": "temp unit convert",
        "name": "temp unit convert",
        "type": "Enum",
        "values": "{\"range\":[\"c\",\"f\"]}"
      },
      {
        "code": "maxtemp_set",
        "desc": "maxtemp set",
        "name": "maxtemp set",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":-400,\"max\":2000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "minitemp_set",
        "desc": "minitemp set",
        "name": "minitemp set",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":-400,\"max\":2000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "maxhum_set",
        "desc": "maxhum set",
        "name": "maxhum set",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "minihum_set",
        "desc": "minihum set",
        "name": "minihum set",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "bright_value",
        "desc": "bright value",
        "name": "bright value",
        "type": "Integer",
        "values": "{\"unit\":\"lux\",\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1644183049559
}`

**Comment by frenck** [comment] 2022-02-06 23:09
@sagioto That has no use, as that isn't standardized, additional that only provides functional information, which without a state, is useless anyways 🤷 

In these cases, there is only  1 thing that can be done: Contact Tuya about your device and hope they can adjust it (which they cannot in all cases, which is often to blame to the manufacturer).

**Comment by marcusforsberg** [comment] 2022-02-07 06:34
I have the same model as @magno-santos (a Nedis sensor and a gateway) and this was Tuya's response:

>  I checked the functions of this product. They are all customized by the device manufacturer and do not conform to the standard instruction set of Tuya Cloud. Therefore, cloud API is not supported to control the device and obtain the status. Use the product on the APP (the device only supports the APP).

Looks like we're out of luck! 😅

**Comment by frenck** [comment] 2022-02-07 08:14
Last possible source/route might be contacting the manufacturer, however, I haven't seen anybody having success with doing that :(

**Comment by sagioto** [comment] 2022-02-09 07:43
I just moved to use ZHA with the sonoff usb zigbee dongle, the sensors work fine that way

**Comment by frenck** [comment] 2022-02-09 08:09
Alright, as you are the reporter of this issue, I'll go ahead and close it.

**Closed by frenck** 2022-02-09 08:09 UTC
Labels: bug
